-- ==========================================
-- ESTRUCTURA DE BASE DE DATOS - INVENTARIO NEXUS
-- Ejecutar en el SQL Editor de Supabase
-- ==========================================

-- 1. Limpieza de tablas (opcional, por si ya existen)
DROP TRIGGER IF EXISTS trg_procesar_movimiento_stock ON movimientos;
DROP FUNCTION IF EXISTS procesar_movimiento_stock();
DROP TABLE IF EXISTS movimientos;
DROP TABLE IF EXISTS productos;
DROP TABLE IF EXISTS categorias;

-- 2. Crear Tabla de Categorías Base
CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);

-- 3. Crear Tabla de Productos (Insumos)
CREATE TABLE productos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    categoria_id BIGINT REFERENCES categorias(id) ON DELETE RESTRICT NOT NULL,
    unidad_medida TEXT NOT NULL, -- kg, g, litros, ml, unidades, paquetes, cajas
    stock_actual NUMERIC NOT NULL DEFAULT 0, -- Inmutable directamente
    stock_minimo NUMERIC NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Crear Tabla de Movimientos
CREATE TABLE movimientos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    producto_id UUID REFERENCES productos(id) ON DELETE CASCADE NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('Entrada', 'Salida')),
    cantidad NUMERIC NOT NULL CHECK (cantidad > 0),
    motivo TEXT NOT NULL,
    usuario_id UUID REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(), -- Asignación automática en Supabase Auth
    usuario_email TEXT, -- Correo registrado del usuario responsable para auditoría directa
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Disparador (Trigger) para Cálculo Automático y Validación de Stock
CREATE OR REPLACE FUNCTION procesar_movimiento_stock()
RETURNS TRIGGER AS $$
DECLARE
    v_stock_actual NUMERIC;
    v_nombre_producto TEXT;
BEGIN
    -- Obtener el stock actual y nombre del producto bloqueando la fila para evitar condiciones de carrera (concurrencia)
    SELECT stock_actual, nombre INTO v_stock_actual, v_nombre_producto
    FROM productos 
    WHERE id = NEW.producto_id
    FOR UPDATE;

    IF v_stock_actual IS NULL THEN
        RAISE EXCEPTION 'Error: El producto especificado no existe.';
    END IF;

    IF NEW.tipo = 'Salida' THEN
        -- Validación de Egreso: No se permite si supera el stock actual
        IF v_stock_actual < NEW.cantidad THEN
            RAISE EXCEPTION 'Stock insuficiente para "%". Stock actual: % %, cantidad solicitada: % %.', 
                v_nombre_producto, v_stock_actual, (SELECT unidad_medida FROM productos WHERE id = NEW.producto_id), 
                NEW.cantidad, (SELECT unidad_medida FROM productos WHERE id = NEW.producto_id);
        END IF;
        
        -- Actualizar restando
        UPDATE productos 
        SET stock_actual = stock_actual - NEW.cantidad 
        WHERE id = NEW.producto_id;
    ELSIF NEW.tipo = 'Entrada' THEN
        -- Actualizar sumando
        UPDATE productos 
        SET stock_actual = stock_actual + NEW.cantidad 
        WHERE id = NEW.producto_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_procesar_movimiento_stock
BEFORE INSERT ON movimientos
FOR EACH ROW
EXECUTE FUNCTION procesar_movimiento_stock();

-- 6. Insertar Categorías Base Obligatorias
INSERT INTO categorias (nombre) VALUES
('Proteínas'),
('Víveres'),
('Verduras y Hortalizas'),
('Lácteos y Refrigerados'),
('Empaques y Descartables');

-- 7. Insertar Datos de Semilla (Productos de Ejemplo)
-- Nota: Inicializan con stock_actual = 0. Se cargará stock mediante movimientos iniciales de Entrada.
INSERT INTO productos (nombre, categoria_id, unidad_medida, stock_minimo) VALUES
('Pechuga de Pollo', (SELECT id FROM categorias WHERE nombre = 'Proteínas'), 'kg', 15.0),
('Carne de Res Molida', (SELECT id FROM categorias WHERE nombre = 'Proteínas'), 'kg', 20.0),
('Arroz Blanco', (SELECT id FROM categorias WHERE nombre = 'Víveres'), 'kg', 50.0),
('Aceite Vegetal', (SELECT id FROM categorias WHERE nombre = 'Víveres'), 'litros', 10.0),
('Tomate', (SELECT id FROM categorias WHERE nombre = 'Verduras y Hortalizas'), 'kg', 8.0),
('Cebolla Cabezoña', (SELECT id FROM categorias WHERE nombre = 'Verduras y Hortalizas'), 'kg', 8.0),
('Queso Doble Crema', (SELECT id FROM categorias WHERE nombre = 'Lácteos y Refrigerados'), 'kg', 5.0),
('Leche Entera', (SELECT id FROM categorias WHERE nombre = 'Lácteos y Refrigerados'), 'litros', 24.0),
('Envase Desechable Almuerzo', (SELECT id FROM categorias WHERE nombre = 'Empaques y Descartables'), 'unidades', 100.0),
('Servilletas de Papel', (SELECT id FROM categorias WHERE nombre = 'Empaques y Descartables'), 'paquetes', 10.0);

-- 8. Registrar Movimientos Iniciales de Entrada para dotar al inventario de stock de prueba
-- Usamos un bloque anónimo para registrar las entradas iniciales
DO $$
DECLARE
    r_prod RECORD;
BEGIN
    FOR r_prod IN SELECT id, nombre FROM productos LOOP
        -- Insertamos una entrada inicial de 35 unidades de promedio
        INSERT INTO movimientos (producto_id, tipo, cantidad, motivo)
        VALUES (r_prod.id, 'Entrada', 35.0, 'Carga inicial de inventario - Semilla');
    END LOOP;
END $$;

-- 9. Registrar algunos movimientos de Salida de prueba para quedar por debajo del mínimo (Alertas de Reabastecimiento)
-- Tomate: stock actual pasa de 35 a 5 (Mínimo es 8, entra en alerta)
-- Queso Doble Crema: stock actual pasa de 35 a 2 (Mínimo es 5, entra en alerta)
DO $$
DECLARE
    v_tomate_id UUID;
    v_queso_id UUID;
BEGIN
    SELECT id INTO v_tomate_id FROM productos WHERE nombre = 'Tomate';
    SELECT id INTO v_queso_id FROM productos WHERE nombre = 'Queso Doble Crema';

    INSERT INTO movimientos (producto_id, tipo, cantidad, motivo)
    VALUES (v_tomate_id, 'Salida', 30.0, 'Preparación ensaladas almuerzo del lunes');

    INSERT INTO movimientos (producto_id, tipo, cantidad, motivo)
    VALUES (v_queso_id, 'Salida', 33.0, 'Preparación de desayunos de la semana');
END $$;

-- 10. Habilitar Seguridad a Nivel de Fila (Row Level Security - RLS)
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimientos ENABLE ROW LEVEL SECURITY;

-- Políticas de Acceso: Permitimos operaciones para usuarios autenticados y anónimos (desarrollo ágil).
-- En un entorno real, restringirías a "authenticated" únicamente.
CREATE POLICY "Permitir todo a anon y authenticated" ON categorias FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a anon y authenticated" ON productos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a anon y authenticated" ON movimientos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
